sensor_kit_base_link:
  camera_link:
    x: 0.385
    y: 0
    z: 0.045
    roll: -1.57079632679
    pitch: 0.0
    yaw: -1.57079632679
  laser:
    x: 0.35
    y: 0
    z: 0.115
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  vesc/imu_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
